### ISSUE TITLE
Переделать "Все вопросы" в список

### ISSUE THREAD

**Issue by soerdev** [soerdev/soer#17]
/pages/qa/all
- отображать вопросы не как список, а как блоки
- если список пуст отображать "No data" стандартный блок

**Comment by resivalex** [comment]
> - отображать вопросы не как список, а как блоки

Не как блоки, а как список?

Список = блоки на полную ширину?

**Comment by soerdev** [comment]
> > * отображать вопросы не как список, а как блоки
> 
> Не как блоки, а как список?
> 
> Список = блоки на полную ширину?

Да, так же как сделан список общих шаблонов целей
