### ISSUE TITLE
Конспекты: сделать textarea на всю высоту экрана

### ISSUE THREAD

**Issue by soerdev** [soerdev/soer#21]
Сейчас текстареа для конспекта занимает только половину экрана, нужно сделать так, чтобы она была на весь экран.

**Comment by mdlufy** [comment]
Сам textarea в режиме edit растягивать до размера контейнера, а сам md block в обычном режиме той же высоты? (второй скрин)
Или и в обычном режиме md block сделать растянутым во всю высоту? (третий скрин)

![image](https://user-images.githubusercontent.com/87331898/178335292-47d09bf1-3dbd-4add-a02f-8e95e690a7ff.png)
![image](https://user-images.githubusercontent.com/87331898/178336138-77e87ea2-e4f4-4412-beed-448d2a72bc87.png)
![image](https://user-images.githubusercontent.com/87331898/178336353-a3a992c5-a34c-4d32-bf5b-554d3cd54b4d.png)

**Comment by soerdev** [comment]
Это уже не актуально, сейчас автосайзинг сделан
